### ISSUE TITLE
Deploy to individual server when added to environment fails due to env vars not being set

### ISSUE THREAD

**Issue by doublerebel** [Distelli/Support#3]
Hello,

When I add a server to an environment from the Dashboard view, and I accept the offer to deploy the app to only that new server, the deployment fails.  I can see from the deploy log that clearly the environment variables set at the top of my `distelli-manifest.yml` are not set.  Re-running a deploy to all servers in the environment works as expected.

I have tried this with multiple apps and multiple environments.  In my case the deploys are to SmartOS instances, the distelli agent doesn't get the 'normal' environment I would get in the default shell so I have to set the path at the head of all my `distelli-manifest`s like so:

``` yaml
- PATH: /usr/local/sbin:/usr/local/bin:/opt/local/sbin:/opt/local/bin:/usr/sbin:/usr/bin:/sbin
```

I see holes in the logs where other env vars I set should appear too, so it's not just `PATH`.
### Example Failure

``` sh
2016-09-30T09:54:49Z Downloading s3://distelli-californians/distelli-packages/optik-security-2016-05-17-23-24-39-a3130924d2f9f3d1e2360d4e6b252672.tar.gz
2016-09-30T09:54:54Z Running /distelli/_apps/optik-security.d-nq91st7lr9332a9ee31/bin/distelli-postinstall.sh
creating  with permissions for ctmpl
usage: touch [-acm] [-r ref_file] file...
       touch [-acm] [-t [[CC]YY]MMDDhhmm[.SS]] file...
       touch [-acm] [-d YYYY-MM-DDThh:mm:SS[.frac][Z]] file...
       touch [-acm] [-d YYYY-MM-DDThh:mm:SS[,frac][Z]] file...
       touch [-acm] [MMDDhhmm[yy]] file...
rendering  once
Consul Template returned errors:
cli: extra argument(s): ["10.2.0.17:8500" "-log-level=debug"]locking down  to ssh user read-only
usage:  chmod [-fR] <absolute-mode> file ...
    chmod [-fR] [-@ attribute] ... S<attribute-operation> file ...
    chmod [-fR] <ACL-operation> file ...
    chmod [-fR] <symbolic-mode-list> file ...

where   <symbolic-mode-list> is a comma-separated list of
    [ugoa]{+|-|=}[rwxXlstugo]

where   <attribute-operation> is a comma-separated list of
    one or more of the following
    [+|-|=]c[<compact-attribute-list>|{<compact-attribute-list>}]
    [+|-|=]v[<verbose-attribute-setting>|'{'<verbose-attribute-setting-list>'}']
    [+|-|=]a
where   <compact-attribute-list> is a list of zero or more of
    [A|H|R|S|a|d|i|m|q|u|O|s]
where   <verbose-attribute-setting> is one of
    [archive|hidden|readonly|system|appendonly|nodump|immutable|av_modified|av_quarantined|nounlink|offline|sparse]
    and can be, optionally, immediately preceded by "no"

where   <ACL-operation> is one of the following
    A-<acl_specification>
    A[number]-
    A[number]{+|=}<acl_specification>
where   <acl-specification> is a comma-separated list of ACEs
installing Duo Login Agent from pkgsrc
duo-unix-1.9.7: /opt/local/etc/login_duo.conf already exists
duo-unix-1.9.7: copying /opt/local/share/examples/duo-unix/pam_duo.conf to /opt/local/etc/pam_duo.conf
duo-unix-1.9.7: setting permissions on /opt/local/sbin/login_duo (o=root, g=root, m=4511)
===========================================================================
The following files are used by duo-unix-1.9.7 and have
the wrong ownership and/or permissions:

    /opt/local/etc/login_duo.conf (m=0400, o=root, g=root)

===========================================================================

calculating dependencies... done.

nothing to upgrade.
1 packages to be installed (121K to download, 296K to install):

duo-unix-1.9.7

downloading packages...
download started.
download ended.
installing packages...
installing duo-unix-1.9.7...
pkg_install warnings: 0, errors: 0
reading local summary...
processing local summary...
marking duo-unix-1.9.7 as non auto-removable
enabling Duo Login Agent for distelli at 
cp: Insufficient arguments (1)
Usage: cp [-a] [-f] [-i] [-p] [-@] [-/] f1 f2
       cp [-a] [-f] [-i] [-p] [-@] [-/] f1 ... fn d1
       cp [-r|-R [-H|-L|-P]] [-a] [-f] [-i] [-p] [-@] [-/] d1 ... dn-1 dn
installing 
cp: Insufficient arguments (1)
Usage: cp [-a] [-f] [-i] [-p] [-@] [-/] f1 f2
       cp [-a] [-f] [-i] [-p] [-@] [-/] f1 ... fn d1
       cp [-r|-R [-H|-L|-P]] [-a] [-f] [-i] [-p] [-@] [-/] d1 ... dn-1 dn
sh: syntax error at line 1: `end of file' unexpected
installing ssh service check to 
sh: syntax error at line 1: `end of file' unexpected
/opt/local/bin/optik-vlan-env: line 2: ifconfig: command not found
grep: illegal option -- o
Usage:  grep [-c|-l|-q] [-r|-R] [-bhHinsvwx] pattern_list [file ...]
    grep [-c|-l|-q] [-r|-R] [-bhHinsvwx] [-e pattern_list]... [-f pattern_file]... [file...]
    grep -E [-c|-l|-q] [-r|-R] [-bhHinsvx] pattern_list [file ...]
    grep -E [-c|-l|-q] [-r|-R] [-bhHinsvx] [-e pattern_list]... [-f pattern_file]... [file...]
    grep -F [-c|-l|-q] [-r|-R] [-bhHinsvx] pattern_list [file ...]
    grep -F [-c|-l|-q] [-bhHinsvx] [-e pattern_list]... [-f pattern_file]... [file...]
/opt/local/bin/optik-vlan-env: line 3: ifconfig: command not found
grep: illegal option -- o
Usage:  grep [-c|-l|-q] [-r|-R] [-bhHinsvwx] pattern_list [file ...]
    grep [-c|-l|-q] [-r|-R] [-bhHinsvwx] [-e pattern_list]... [-f pattern_file]... [file...]
    grep -E [-c|-l|-q] [-r|-R] [-bhHinsvx] pattern_list [file ...]
    grep -E [-c|-l|-q] [-r|-R] [-bhHinsvx] [-e pattern_list]... [-f pattern_file]... [file...]
    grep -F [-c|-l|-q] [-r|-R] [-bhHinsvx] pattern_list [file ...]
    grep -F [-c|-l|-q] [-bhHinsvx] [-e pattern_list]... [-f pattern_file]... [file...]
/opt/local/bin/optik-vlan-env: line 4: ifconfig: command not found
grep: illegal option -- o
Usage:  grep [-c|-l|-q] [-r|-R] [-bhHinsvwx] pattern_list [file ...]
    grep [-c|-l|-q] [-r|-R] [-bhHinsvwx] [-e pattern_list]... [-f pattern_file]... [file...]
    grep -E [-c|-l|-q] [-r|-R] [-bhHinsvx] pattern_list [file ...]
    grep -E [-c|-l|-q] [-r|-R] [-bhHinsvx] [-e pattern_list]... [-f pattern_file]... [file...]
    grep -F [-c|-l|-q] [-r|-R] [-bhHinsvx] pattern_list [file ...]
    grep -F [-c|-l|-q] [-bhHinsvx] [-e pattern_list]... [-f pattern_file]... [file...]
sed: -I or -i may not be used with stdin
sudo: svcadm: command not found
FAILED: sudo svcadm restart consul
2016-09-30T09:55:02Z /distelli/_apps/optik-security.d-nq91st7lr9332a9ee31/bin/distelli-postinstall.sh exited with 1 exit code (signal=0) during Deploy:PostInstalling

PostInstallFailed
```

I can send more logs privately if needed.

I don't mind setting the path, but it would be nice (and easier on resources) to be able to deploy to a single server without error.

Thanks again for a great tool!  I just rolled over my entire infrastructure for upgrades and Distelli dutifully built it back together with ease.

**Comment by doct15** [comment]
Hi.
I tried to reproduce this issue, to no avail. 

As a recommendation, you should wrap that yaml entry in single quotes due to the colons.

```
    - 'PATH: /usr/local/sbin:/usr/local/bin:/opt/local/sbin:/opt/local/bin:/usr/sbin:/usr/bin:/sbin'
```

Also, it is helpful to add some debug commands to your manifest to validate your environment variables are set.

```
  Env:
    - 'PATH: /usr/local/sbin:/usr/local/bin:/opt/local/sbin:/opt/local/bin:/usr/sbin:/usr/bin:/sbin'
  PostInstall:
    - echo "PostInstall"
    - echo "PATH is $PATH"
```

Please let me know if this doesn't work for you.
-Regards.

**Comment by doublerebel** [comment]
The YAML entry is the same across all my 20+ apps, but the issue only appears if I add a new server to an environment and deploy to it.  I do this from the Dashboard view.  I tried again today with a different app just to check, and the bug still exists:

```sh

2016-10-23T22:27:29Z Downloading s3://distelli-californians/distelli-packages/nextorigin-el-borracho-2016-10-23-22-00-07-326b03d5e44f645f54fa5464b38738f8.tar.gz
2016-10-23T22:28:17Z Running /distelli/apps/nextorigin-el-borracho/bin/distelli-run.sh
2016-10-23T22:28:17Z started '/distelli/apps/nextorigin-el-borracho/bin/distelli-run.sh' with pid 92597
starting el-borracho
/opt/local/bin/optik-vlan-env: line 2: ifconfig: command not found
grep: illegal option -- o
Usage:	grep [-c|-l|-q] [-r|-R] [-bhHinsvwx] pattern_list [file ...]
	grep [-c|-l|-q] [-r|-R] [-bhHinsvwx] [-e pattern_list]... [-f pattern_file]... [file...]
	grep -E [-c|-l|-q] [-r|-R] [-bhHinsvx] pattern_list [file ...]
	grep -E [-c|-l|-q] [-r|-R] [-bhHinsvx] [-e pattern_list]... [-f pattern_file]... [file...]
	grep -F [-c|-l|-q] [-r|-R] [-bhHinsvx] pattern_list [file ...]
	grep -F [-c|-l|-q] [-bhHinsvx] [-e pattern_list]... [-f pattern_file]... [file...]
/opt/local/bin/optik-vlan-env: line 3: ifconfig: command not found
grep: illegal option -- o
Usage:	grep [-c|-l|-q] [-r|-R] [-bhHinsvwx] pattern_list [file ...]
	grep [-c|-l|-q] [-r|-R] [-bhHinsvwx] [-e pattern_list]... [-f pattern_file]... [file...]
	grep -E [-c|-l|-q] [-r|-R] [-bhHinsvx] pattern_list [file ...]
	grep -E [-c|-l|-q] [-r|-R] [-bhHinsvx] [-e pattern_list]... [-f pattern_file]... [file...]
	grep -F [-c|-l|-q] [-r|-R] [-bhHinsvx] pattern_list [file ...]
	grep -F [-c|-l|-q] [-bhHinsvx] [-e pattern_list]... [-f pattern_file]... [file...]
/opt/local/bin/optik-vlan-env: line 4: ifconfig: command not found
grep: illegal option -- o
Usage:	grep [-c|-l|-q] [-r|-R] [-bhHinsvwx] pattern_list [file ...]
	grep [-c|-l|-q] [-r|-R] [-bhHinsvwx] [-e pattern_list]... [-f pattern_file]... [file...]
	grep -E [-c|-l|-q] [-r|-R] [-bhHinsvx] pattern_list [file ...]
	grep -E [-c|-l|-q] [-r|-R] [-bhHinsvx] [-e pattern_list]... [-f pattern_file]... [file...]
	grep -F [-c|-l|-q] [-r|-R] [-bhHinsvx] pattern_list [file ...]
	grep -F [-c|-l|-q] [-bhHinsvx] [-e pattern_list]... [-f pattern_file]... [file...]
debug: (Flannel:init) flannel 0.9.5: feel like a lumberjack
debug: (El Borracho) initializing
debug: (El Borracho) registering with Consul
{ Error: connect ECONNREFUSED 127.0.0.1:8500
    at Object.exports._errnoException (util.js:1007:11)
    at exports._exceptionWithHostPort (util.js:1030:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 8500 }
2016-10-23T22:28:19Z Process `/distelli/apps/nextorigin-el-borracho/bin/distelli-run.sh` failed to run for longer than 5 second(s). during Deploy:Starting
```

**Comment by doct15** [comment]
Hi.
Were you able to add some debug information to your manifest for validation?
  Env:
    - 'PATH: /usr/local/sbin:/usr/local/bin:/opt/local/sbin:/opt/local/bin:/usr/sbin:/usr/bin:/sbin'
  PostInstall:
    - echo "PostInstall"
    - echo "PATH is $PATH"

I can see in your release that was deployed, the export PATH statement appears to be there.
/releases/a-ha1sk97wsxace04e8d16?section=manifest

But, looking at the failed deployment, it appears it failed to connect to a local service
debug: (El Borracho) registering with Consul
{ Error: connect ECONNREFUSED 127.0.0.1:8500

I would further add the following debug to your manifest before running:
optik-vlan-env node lib/nextorigin-el-borracho.js

netstat -an | grep "LISTEN "

and validate you have a process listening on port 8500

Hope that helps.

**Comment by doublerebel** [comment]
All the failures are due to the environment not being set correctly.  The grep errors are due to it finding the wrong grep (there are a couple versions of unix tools on SmartOS, one is traditional Solaris and one matches GNU/Linux syntax).  There is no process listening on localhost, my setup relies on a couple env vars to point it to the various VLANs.  When I get a chance to setup a test case I'll run `env` in the script to see what we can find.

**Comment by doublerebel** [comment]
It appears that as in #4 this problem does not exist directly on the page for the environment, only when administrating for the dashboard.  Still a bug I suppose, but that workaround is OK for now.

**Comment by doct15** [comment]
Hi. Thank you for your patience and helping us delve into this issue.

We were able to reproduce the issue and have an engineer looking into a fix.

**Comment by doct15** [comment]
This issue is fixed!
